// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4AvgTa4ggzD1kflvlMwUUCMAptYMHdHU',
    appId: '1:1092464298683:web:c5ac5e804b0a96c8a5379e',
    messagingSenderId: '1092464298683',
    projectId: 'penjualanbuku-46f7e',
    authDomain: 'penjualanbuku-46f7e.firebaseapp.com',
    storageBucket: 'penjualanbuku-46f7e.firebasestorage.app',
    measurementId: 'G-6H0QH2038S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7CKXWpLDwV3rtMsn3KklKWaBDx2TcQs8',
    appId: '1:1092464298683:android:6c0e931db9b78a9ba5379e',
    messagingSenderId: '1092464298683',
    projectId: 'penjualanbuku-46f7e',
    storageBucket: 'penjualanbuku-46f7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF2XbWMHZehAXVJBiFFlBI2Y23q1cc36I',
    appId: '1:1092464298683:ios:8b24b56d775a4a39a5379e',
    messagingSenderId: '1092464298683',
    projectId: 'penjualanbuku-46f7e',
    storageBucket: 'penjualanbuku-46f7e.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF2XbWMHZehAXVJBiFFlBI2Y23q1cc36I',
    appId: '1:1092464298683:ios:8b24b56d775a4a39a5379e',
    messagingSenderId: '1092464298683',
    projectId: 'penjualanbuku-46f7e',
    storageBucket: 'penjualanbuku-46f7e.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4AvgTa4ggzD1kflvlMwUUCMAptYMHdHU',
    appId: '1:1092464298683:web:e20ba9748aee2241a5379e',
    messagingSenderId: '1092464298683',
    projectId: 'penjualanbuku-46f7e',
    authDomain: 'penjualanbuku-46f7e.firebaseapp.com',
    storageBucket: 'penjualanbuku-46f7e.firebasestorage.app',
    measurementId: 'G-456FRD1030',
  );
}
